language: objective-c
xcode_workspace: FlushCapacitor.xcworkspace
xcode_scheme: FlushCapacitor
env:
  global:
    secure: cNqH4o8kEFTJFSO6KGl4FkI+WQffjm5GJ/VApQ4vj680mpkr8AEzUn9lDI5gxznvpIx0pvpagT4oExDpU5Nt1jON6g4Get5tm60X+cHiN01Cuiiy01TXlz0Erky5+IhCO737PoJ6zqVWK+YaX/hqaVpWaVc40zocayu62FkPeos=
after_success:
  ./scripts/hockey.sh develop

